# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cards',
                'doc_host': 'https://prp0x80.github.io',
                'git_url': 'https://github.com/prp0x80/nbdev_cards',
                'lib_path': 'nbdev_cards'},
  'syms': { 'nbdev_cards.card': { 'nbdev_cards.card.Card': ('card.html#card', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__init__': ('card.html#card.__init__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__str__': ('card.html#card.__str__', 'nbdev_cards/card.py')}}}